//! Deterministic Java 17 schema-table generation.
//!
//! Vox's Java target owns ergonomic DTOs and adapters. This lower-level target
//! emits the canonical Phon bytes and root ids those adapters are derived from.

use std::fmt::Write;

use phon_schema::schema_to_bytes;

use crate::Module;

#[must_use]
pub fn render_schema_table(module: &Module, package: &str, class_name: &str) -> String {
    let mut out = format!(
        "// @generated by phon-codegen; DO NOT EDIT.\npackage {package};\n\n\
         public final class {class_name} {{\n"
    );
    for root in &module.roots {
        let _ = writeln!(
            out,
            "  public static final long {}_SCHEMA_ID = 0x{:016x}L;",
            java_constant(&root.name),
            root.id.as_u64()
        );
    }
    out.push_str("  public static final byte[][] CANONICAL_SCHEMAS = {\n");
    for schema in &module.schemas {
        let bytes = schema_to_bytes(schema)
            .iter()
            .map(|byte| format!("(byte)0x{byte:02x}"))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "    new byte[] {{{bytes}}},");
    }
    out.push_str("  };\n");
    let _ = writeln!(out, "  private {class_name}() {{}}");
    out.push_str("}\n");
    out
}

fn java_constant(name: &str) -> String {
    name.chars()
        .flat_map(|character| {
            if character.is_ascii_uppercase() {
                vec!['_', character]
            } else if character.is_ascii_alphanumeric() {
                vec![character.to_ascii_uppercase()]
            } else {
                vec!['_']
            }
        })
        .collect::<String>()
        .trim_start_matches('_')
        .to_string()
}

#[cfg(test)]
mod tests {
    use facet::Facet;

    use crate::Builder;

    use super::render_schema_table;

    #[derive(Facet)]
    struct Message {
        text: String,
    }

    #[test]
    fn schema_table_is_deterministic_and_contains_canonical_root() {
        let module = Builder::new()
            .add::<Message>()
            .build()
            .expect("derive schema");
        let first = render_schema_table(&module, "org.facet.phon.generated", "FixtureSchemas");
        let second = render_schema_table(&module, "org.facet.phon.generated", "FixtureSchemas");
        assert_eq!(first, second);
        assert!(first.contains("MESSAGE_SCHEMA_ID = 0x"));
        assert!(first.contains("new byte[]"));
        assert!(first.contains("private FixtureSchemas()"));
    }
}
