//! Java 17 source generation for the supported unary Vox slice.

use std::collections::HashSet;
use std::fmt::{self, Write};

use facet_core::{ScalarType, Shape};
use phon_schema::schema_to_bytes;
use vox_types::{
    EnumInfo, MethodDescriptor, ServiceDescriptor, ShapeKind, StructInfo, VariantKind,
    classify_shape, classify_variant, is_bytes,
};

/// One deterministic Java compilation unit.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct JavaFile {
    pub relative_path: String,
    pub source: String,
}

/// A focused generation error. Java generation is deliberately fallible because
/// the first Java runtime accepts a smaller shape/transport surface than Rust.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct JavaCodegenError {
    pub service: String,
    pub method: String,
    pub detail: String,
}

impl fmt::Display for JavaCodegenError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "Java codegen does not support {}.{}: {}",
            self.service, self.method, self.detail
        )
    }
}

impl std::error::Error for JavaCodegenError {}

/// Generate DTO, descriptor, handler, dispatcher, and caller compilation units.
///
/// Files are sorted by relative path and contain no timestamps, so two runs for
/// the same descriptor are byte-identical.
pub fn generate_service(service: &ServiceDescriptor) -> Result<Vec<JavaFile>, JavaCodegenError> {
    validate_service(service)?;
    let package = "org.facet.vox.generated";
    let service_name = java_type_name(service.service_name);
    let named = collect_named_types(service);
    let mut files = vec![JavaFile {
        relative_path: "PrimitiveAdapters.java".to_string(),
        source: generate_primitive_adapters(package),
    }];

    for (name, shape) in named {
        files.push(JavaFile {
            relative_path: format!("{name}.java"),
            source: generate_named_type(package, &name, shape),
        });
    }
    for method in service.methods {
        let args_name = args_type_name(&service_name, method);
        files.push(JavaFile {
            relative_path: format!("{args_name}.java"),
            source: generate_args_type(package, &args_name, method),
        });
        let response_name = response_type_name(&service_name, method);
        files.push(JavaFile {
            relative_path: format!("{response_name}.java"),
            source: generate_response_type(package, &response_name, method)?,
        });
    }
    files.push(JavaFile {
        relative_path: format!("{service_name}ServiceDescriptor.java"),
        source: generate_descriptor(package, &service_name, service),
    });
    files.push(JavaFile {
        relative_path: format!("{service_name}Handler.java"),
        source: generate_handler(package, &service_name, service),
    });
    files.push(JavaFile {
        relative_path: format!("{service_name}Dispatcher.java"),
        source: generate_dispatcher(package, &service_name, service),
    });
    files.push(JavaFile {
        relative_path: format!("{service_name}Client.java"),
        source: generate_client(package, &service_name, service),
    });
    files.sort_by(|a, b| a.relative_path.cmp(&b.relative_path));
    Ok(files)
}

/// Generate the canonical connection-envelope and handshake schema tables.
///
/// The emitted bytes and root ids are derived from the Rust `vox-types` shapes;
/// Java never re-derives protocol schema identity or duplicates variant order.
pub fn generate_wire_schemas() -> Result<Vec<JavaFile>, phon::derive::DeriveError> {
    use facet::Facet;
    use phon_codegen::Module;
    use phon_codegen::targets::java::render_schema_table;
    use vox_types as wire;

    let message = Module::from_shapes(&[<wire::Message<'static> as Facet<'static>>::SHAPE])?;
    let handshake = Module::from_shapes(&[<wire::HandshakeMessage as Facet<'static>>::SHAPE])?;
    Ok(vec![
        JavaFile {
            relative_path: "HandshakeWireSchemas.java".to_string(),
            source: render_schema_table(
                &handshake,
                "org.facet.vox.generated",
                "HandshakeWireSchemas",
            ),
        },
        JavaFile {
            relative_path: "MessageWireSchemas.java".to_string(),
            source: render_schema_table(&message, "org.facet.vox.generated", "MessageWireSchemas"),
        },
    ])
}

fn header(package: &str) -> String {
    format!(
        "// @generated by vox-codegen; DO NOT EDIT.\n\
         // Regenerate with `cargo xtask codegen --java`.\n\
         package {package};\n\n"
    )
}

fn validate_service(service: &ServiceDescriptor) -> Result<(), JavaCodegenError> {
    for method in service.methods {
        if method.args_have_channels
            || vox_types::shape_contains_channel(method.args_shape)
            || vox_types::shape_contains_channel(method.return_shape)
        {
            return Err(error(
                method,
                "channels are outside the Java 17 unary slice",
            ));
        }
        validate_shape(method, method.args_shape, "arguments")?;
        validate_shape(method, method.return_shape, "return type")?;
    }
    Ok(())
}

fn validate_shape(
    method: &MethodDescriptor,
    shape: &'static Shape,
    location: &str,
) -> Result<(), JavaCodegenError> {
    if is_bytes(shape) {
        return Ok(());
    }
    if matches!(shape.def, facet_core::Def::DynamicValue(_)) {
        return Err(error(method, &format!("dynamic Facet value in {location}")));
    }
    #[cfg(unix)]
    if vox_types::is_fd(shape) {
        return Err(error(
            method,
            &format!("file descriptor capability in {location}"),
        ));
    }
    match classify_shape(shape) {
        ShapeKind::Opaque => Err(error(
            method,
            &format!(
                "opaque or external shape `{}` in {location}",
                shape.type_identifier
            ),
        )),
        ShapeKind::Tx { .. } | ShapeKind::Rx { .. } => {
            Err(error(method, &format!("channel in {location}")))
        }
        ShapeKind::List { .. }
        | ShapeKind::Slice { .. }
        | ShapeKind::Set { .. }
        | ShapeKind::Array { .. }
        | ShapeKind::Option { .. }
        | ShapeKind::Map { .. } => Err(error(
            method,
            &format!(
                "container shape `{}` in {location} is not implemented yet",
                shape.type_identifier
            ),
        )),
        ShapeKind::Pointer { pointee } => validate_shape(method, pointee, location),
        ShapeKind::Result {
            ok: key,
            err: value,
        } => {
            validate_shape(method, key, location)?;
            validate_shape(method, value, location)
        }
        ShapeKind::Tuple { elements } => {
            for element in elements {
                validate_shape(method, element.shape, location)?;
            }
            Ok(())
        }
        ShapeKind::TupleStruct { fields } | ShapeKind::Struct(StructInfo { fields, .. }) => {
            for field in fields {
                validate_shape(method, field.shape(), location)?;
            }
            Ok(())
        }
        ShapeKind::Enum(EnumInfo { variants, .. }) => {
            for variant in variants {
                match classify_variant(variant) {
                    VariantKind::Unit => {}
                    VariantKind::Newtype { .. }
                    | VariantKind::Tuple { .. }
                    | VariantKind::Struct { .. } => {
                        return Err(error(
                            method,
                            &format!(
                                "payload enum `{}` in {location} is not implemented yet",
                                shape.type_identifier
                            ),
                        ));
                    }
                }
            }
            Ok(())
        }
        ShapeKind::Scalar(
            ScalarType::Bool
            | ScalarType::U8
            | ScalarType::U16
            | ScalarType::U32
            | ScalarType::I8
            | ScalarType::I16
            | ScalarType::I32
            | ScalarType::I64
            | ScalarType::F32
            | ScalarType::F64
            | ScalarType::Str
            | ScalarType::String
            | ScalarType::CowStr,
        ) => Ok(()),
        ShapeKind::Scalar(_) => Err(error(
            method,
            &format!(
                "scalar shape `{}` in {location} is not implemented yet",
                shape.type_identifier
            ),
        )),
    }
}

fn error(method: &MethodDescriptor, detail: &str) -> JavaCodegenError {
    JavaCodegenError {
        service: method.service_name.to_string(),
        method: method.method_name.to_string(),
        detail: detail.to_string(),
    }
}

fn collect_named_types(service: &ServiceDescriptor) -> Vec<(String, &'static Shape)> {
    let mut seen = HashSet::new();
    let mut result = Vec::new();
    for method in service.methods {
        visit_named(method.args_shape, &mut seen, &mut result);
        visit_named(method.return_shape, &mut seen, &mut result);
    }
    result.sort_by(|a, b| a.0.cmp(&b.0));
    result
}

fn visit_named(
    shape: &'static Shape,
    seen: &mut HashSet<String>,
    result: &mut Vec<(String, &'static Shape)>,
) {
    match classify_shape(shape) {
        ShapeKind::Struct(StructInfo {
            name: Some(name),
            fields,
            ..
        }) => {
            for field in fields {
                visit_named(field.shape(), seen, result);
            }
            if seen.insert(name.to_string()) {
                result.push((java_type_name(name), shape));
            }
        }
        ShapeKind::Enum(EnumInfo {
            name: Some(name),
            variants,
        }) => {
            for variant in variants {
                match classify_variant(variant) {
                    VariantKind::Unit => {}
                    VariantKind::Newtype { inner } => visit_named(inner, seen, result),
                    VariantKind::Tuple { fields } | VariantKind::Struct { fields } => {
                        for field in fields {
                            visit_named(field.shape(), seen, result);
                        }
                    }
                }
            }
            if seen.insert(name.to_string()) {
                result.push((java_type_name(name), shape));
            }
        }
        ShapeKind::List { element }
        | ShapeKind::Slice { element }
        | ShapeKind::Set { element }
        | ShapeKind::Array { element, .. }
        | ShapeKind::Option { inner: element }
        | ShapeKind::Pointer { pointee: element } => visit_named(element, seen, result),
        ShapeKind::Map { key, value }
        | ShapeKind::Result {
            ok: key,
            err: value,
        } => {
            visit_named(key, seen, result);
            visit_named(value, seen, result);
        }
        ShapeKind::Tuple { elements } => {
            for element in elements {
                visit_named(element.shape, seen, result);
            }
        }
        ShapeKind::TupleStruct { fields } => {
            for field in fields {
                visit_named(field.shape(), seen, result);
            }
        }
        ShapeKind::Struct(StructInfo {
            name: None, fields, ..
        }) => {
            for field in fields {
                visit_named(field.shape(), seen, result);
            }
        }
        ShapeKind::Enum(EnumInfo {
            name: None,
            variants,
        }) => {
            for variant in variants {
                match classify_variant(variant) {
                    VariantKind::Unit => {}
                    VariantKind::Newtype { inner } => visit_named(inner, seen, result),
                    VariantKind::Tuple { fields } | VariantKind::Struct { fields } => {
                        for field in fields {
                            visit_named(field.shape(), seen, result);
                        }
                    }
                }
            }
        }
        ShapeKind::Scalar(_) | ShapeKind::Tx { .. } | ShapeKind::Rx { .. } | ShapeKind::Opaque => {}
    }
}

fn generate_named_type(package: &str, name: &str, shape: &'static Shape) -> String {
    match classify_shape(shape) {
        ShapeKind::Struct(StructInfo { fields, .. }) => {
            let mut out = header(package);
            out.push_str("import java.util.List;\nimport java.util.Objects;\n");
            out.push_str("import org.facet.phon.*;\n\n");
            let _ = writeln!(out, "public final class {name} {{");
            for field in fields {
                let _ = writeln!(
                    out,
                    "  private final {} {};",
                    java_type(field.shape(), false),
                    java_ident(field.name)
                );
            }
            out.push('\n');
            let args = fields
                .iter()
                .map(|f| format!("{} {}", java_type(f.shape(), false), java_ident(f.name)))
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(out, "  public {name}({args}) {{");
            for field in fields {
                let field_name = java_ident(field.name);
                if is_reference(field.shape()) && !is_option(field.shape()) {
                    let _ = writeln!(
                        out,
                        "    this.{field_name} = Objects.requireNonNull({field_name}, \"{field_name}\");"
                    );
                } else {
                    let _ = writeln!(out, "    this.{field_name} = {field_name};");
                }
            }
            out.push_str("  }\n\n");
            for field in fields {
                let field_name = java_ident(field.name);
                let _ = writeln!(
                    out,
                    "  public {} {}() {{ return {}; }}",
                    java_type(field.shape(), false),
                    field_name,
                    field_name
                );
            }
            out.push('\n');
            emit_record_schema_and_adapter(&mut out, name, shape, fields);
            out.push_str("\n  @Override public boolean equals(Object other) {\n");
            let _ = writeln!(
                out,
                "    if (!(other instanceof {name} that)) return false;"
            );
            let comparisons = fields
                .iter()
                .map(|f| {
                    let n = java_ident(f.name);
                    format!("Objects.deepEquals({n}, that.{n})")
                })
                .collect::<Vec<_>>()
                .join(" && ");
            let _ = writeln!(
                out,
                "    return {};",
                if comparisons.is_empty() {
                    "true"
                } else {
                    &comparisons
                }
            );
            out.push_str("  }\n");
            let names = fields
                .iter()
                .map(|f| java_ident(f.name))
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(
                out,
                "  @Override public int hashCode() {{ return Objects.hash({names}); }}"
            );
            let _ = writeln!(
                out,
                "  @Override public String toString() {{ return \"{name}\" + java.util.List.of({names}); }}"
            );
            out.push_str("}\n");
            out
        }
        ShapeKind::Enum(EnumInfo { variants, .. })
            if variants
                .iter()
                .all(|v| matches!(classify_variant(v), VariantKind::Unit)) =>
        {
            let mut out = header(package);
            out.push_str("import java.util.List;\nimport org.facet.phon.*;\n\n");
            let constants = variants
                .iter()
                .map(|v| java_enum_constant(v.name))
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(out, "public enum {name} {{ {constants};");
            let id = schema_id(shape);
            let variant_exprs = variants
                .iter()
                .enumerate()
                .map(|(index, variant)| {
                    format!(
                        "new Schema.Variant(\"{}\", {index}, Schema.Payload.unit())",
                        variant.name
                    )
                })
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(
                out,
                "  public static final Schema SCHEMA = new Schema(SchemaId.fromLong(0x{id:016x}L), List.of(), new Schema.EnumKind(\"{name}\", List.of({variant_exprs})));"
            );
            let _ = writeln!(
                out,
                "  public static final PhonAdapter<{name}> ADAPTER = new PhonAdapter<>() {{"
            );
            out.push_str("    @Override public SchemaClosure schema() { return SchemaClosure.uncheckedOf(SCHEMA); }\n");
            out.push_str("    @Override public void encode(PhonEncoder encoder, ");
            let _ = writeln!(
                out,
                "{name} value) throws PhonException {{ encoder.writeU32(value.ordinal()); }}"
            );
            let _ = writeln!(
                out,
                "    @Override public {name} decode(PhonDecoder decoder) throws PhonException {{ long value = decoder.readU32(); if (value >= values().length) throw new PhonException(PhonException.Kind.MALFORMED, \"invalid {name} discriminant \" + value); return values()[(int) value]; }}"
            );
            out.push_str("  };\n");
            out.push_str("}\n");
            out
        }
        _ => {
            let mut out = header(package);
            let _ = writeln!(
                out,
                "// Shape `{name}` is referenced through its generated adapter."
            );
            let _ = writeln!(out, "public final class {name} {{ private {name}() {{}} }}");
            out
        }
    }
}

fn generate_args_type(package: &str, name: &str, method: &MethodDescriptor) -> String {
    let mut out = header(package);
    out.push_str("import java.util.List;\nimport java.util.Objects;\nimport org.facet.phon.*;\n\n");
    let _ = writeln!(out, "public final class {name} {{");
    for arg in method.args {
        let _ = writeln!(
            out,
            "  private final {} {};",
            java_type(arg.shape, false),
            java_ident(arg.name)
        );
    }
    let args = method
        .args
        .iter()
        .map(|arg| format!("{} {}", java_type(arg.shape, false), java_ident(arg.name)))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(out, "  public {name}({args}) {{");
    for arg in method.args {
        let arg_name = java_ident(arg.name);
        if is_reference(arg.shape) && !is_option(arg.shape) {
            let _ = writeln!(
                out,
                "    this.{arg_name} = Objects.requireNonNull({arg_name}, \"{arg_name}\");"
            );
        } else {
            let _ = writeln!(out, "    this.{arg_name} = {arg_name};");
        }
    }
    out.push_str("  }\n");
    for arg in method.args {
        let arg_name = java_ident(arg.name);
        let _ = writeln!(
            out,
            "  public {} {}() {{ return {}; }}",
            java_type(arg.shape, false),
            arg_name,
            arg_name
        );
    }
    let id = schema_id(method.args_shape);
    let refs = method
        .args
        .iter()
        .map(|arg| schema_ref_expr(arg.shape))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(
        out,
        "  public static final Schema SCHEMA = new Schema(SchemaId.fromLong(0x{id:016x}L), List.of(), new Schema.TupleKind(List.of({refs})));"
    );
    let _ = writeln!(
        out,
        "  public static final PhonAdapter<{name}> ADAPTER = new PhonAdapter<>() {{"
    );
    let reachables = method
        .args
        .iter()
        .filter_map(|arg| named_shape_name(arg.shape))
        .map(|n| format!("{n}.SCHEMA"))
        .collect::<Vec<_>>()
        .join(", ");
    let closure = if reachables.is_empty() {
        "SchemaClosure.uncheckedOf(SCHEMA)".to_string()
    } else {
        format!("SchemaClosure.uncheckedOf(SCHEMA, {reachables})")
    };
    let _ = writeln!(
        out,
        "    @Override public SchemaClosure schema() {{ return {closure}; }}"
    );
    let _ = writeln!(
        out,
        "    @Override public void encode(PhonEncoder encoder, {name} value) throws PhonException {{"
    );
    for arg in method.args {
        let _ = writeln!(
            out,
            "      {}",
            encode_statement(arg.shape, &format!("value.{}()", java_ident(arg.name)))
        );
    }
    out.push_str("    }\n");
    let decoded = method
        .args
        .iter()
        .map(|arg| decode_expression(arg.shape))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(
        out,
        "    @Override public {name} decode(PhonDecoder decoder) throws PhonException {{ return new {name}({decoded}); }}"
    );
    out.push_str("  };\n");
    out.push_str("}\n");
    out
}

fn emit_record_schema_and_adapter(
    out: &mut String,
    name: &str,
    shape: &'static Shape,
    fields: &[facet_core::Field],
) {
    let id = schema_id(shape);
    let field_exprs = fields
        .iter()
        .map(|field| {
            format!(
                "new Schema.Field(\"{}\", {}, true)",
                field.name,
                schema_ref_expr(field.shape())
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(
        out,
        "  public static final Schema SCHEMA = new Schema(SchemaId.fromLong(0x{id:016x}L), List.of(), new Schema.RecordKind(\"{name}\", List.of({field_exprs})));"
    );
    let _ = writeln!(
        out,
        "  public static final PhonAdapter<{name}> ADAPTER = new PhonAdapter<>() {{"
    );
    let reachables = fields
        .iter()
        .filter_map(|field| named_shape_name(field.shape()))
        .map(|nested| format!("{nested}.SCHEMA"))
        .collect::<Vec<_>>()
        .join(", ");
    let closure = if reachables.is_empty() {
        "SchemaClosure.uncheckedOf(SCHEMA)".to_string()
    } else {
        format!("SchemaClosure.uncheckedOf(SCHEMA, {reachables})")
    };
    let _ = writeln!(
        out,
        "    @Override public SchemaClosure schema() {{ return {closure}; }}"
    );
    let _ = writeln!(
        out,
        "    @Override public void encode(PhonEncoder encoder, {name} value) throws PhonException {{"
    );
    for field in fields {
        let _ = writeln!(
            out,
            "      {}",
            encode_statement(
                field.shape(),
                &format!("value.{}()", java_ident(field.name))
            )
        );
    }
    out.push_str("    }\n");
    let decoded = fields
        .iter()
        .map(|field| decode_expression(field.shape()))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(
        out,
        "    @Override public {name} decode(PhonDecoder decoder) throws PhonException {{ return new {name}({decoded}); }}"
    );
    out.push_str("  };\n");
}

fn schema_id(shape: &'static Shape) -> u64 {
    vox_phon::schema_id_for_shape(shape)
        .unwrap_or_else(|error| {
            panic!(
                "Java schema generation failed for `{}`: {error}",
                shape.type_identifier
            )
        })
        .as_u64()
}

fn schema_ref_expr(shape: &'static Shape) -> String {
    format!(
        "Schema.Ref.concrete(SchemaId.fromLong(0x{:016x}L))",
        schema_id(shape)
    )
}

fn named_shape_name(shape: &'static Shape) -> Option<String> {
    match classify_shape(shape) {
        ShapeKind::Struct(StructInfo {
            name: Some(name), ..
        })
        | ShapeKind::Enum(EnumInfo {
            name: Some(name), ..
        }) => Some(java_type_name(name)),
        _ => None,
    }
}

fn encode_statement(shape: &'static Shape, value: &str) -> String {
    match classify_shape(shape) {
        ShapeKind::Scalar(ScalarType::Bool) => format!("encoder.writeBool({value});"),
        ShapeKind::Scalar(ScalarType::U8) => format!("encoder.writeU8({value});"),
        ShapeKind::Scalar(ScalarType::U16) => format!("encoder.writeU16({value});"),
        ShapeKind::Scalar(ScalarType::U32) => format!("encoder.writeU32({value});"),
        ShapeKind::Scalar(ScalarType::I8) => format!("encoder.writeI8({value});"),
        ShapeKind::Scalar(ScalarType::I16) => format!("encoder.writeI16({value});"),
        ShapeKind::Scalar(ScalarType::I32) => format!("encoder.writeI32({value});"),
        ShapeKind::Scalar(ScalarType::I64) => format!("encoder.writeI64({value});"),
        ShapeKind::Scalar(ScalarType::F32) => format!("encoder.writeF32({value});"),
        ShapeKind::Scalar(ScalarType::F64) => format!("encoder.writeF64({value});"),
        ShapeKind::Scalar(ScalarType::Char) => format!("encoder.writeChar({value});"),
        ShapeKind::Scalar(ScalarType::Str | ScalarType::String | ScalarType::CowStr) => {
            format!("encoder.writeString({value});")
        }
        ShapeKind::Struct(StructInfo {
            name: Some(name), ..
        })
        | ShapeKind::Enum(EnumInfo {
            name: Some(name), ..
        }) => format!(
            "encoder.writeAdapted({}.ADAPTER, {value});",
            java_type_name(name)
        ),
        _ if is_bytes(shape) => format!("encoder.writeBytes({value});"),
        _ => format!(
            "throw new PhonException(PhonException.Kind.DECODE, \"generated adapter for {} is not implemented\");",
            shape.type_identifier.replace('"', "\\\"")
        ),
    }
}

fn decode_expression(shape: &'static Shape) -> String {
    match classify_shape(shape) {
        ShapeKind::Scalar(ScalarType::Bool) => "decoder.readBool()".into(),
        ShapeKind::Scalar(ScalarType::U8) => "decoder.readU8()".into(),
        ShapeKind::Scalar(ScalarType::U16) => "decoder.readU16()".into(),
        ShapeKind::Scalar(ScalarType::U32) => "decoder.readU32()".into(),
        ShapeKind::Scalar(ScalarType::I8) => "decoder.readI8()".into(),
        ShapeKind::Scalar(ScalarType::I16) => "decoder.readI16()".into(),
        ShapeKind::Scalar(ScalarType::I32) => "decoder.readI32()".into(),
        ShapeKind::Scalar(ScalarType::I64) => "decoder.readI64()".into(),
        ShapeKind::Scalar(ScalarType::F32) => "decoder.readF32()".into(),
        ShapeKind::Scalar(ScalarType::F64) => "decoder.readF64()".into(),
        ShapeKind::Scalar(ScalarType::Char) => "decoder.readChar()".into(),
        ShapeKind::Scalar(ScalarType::Str | ScalarType::String | ScalarType::CowStr) => {
            "decoder.readString()".into()
        }
        ShapeKind::Struct(StructInfo {
            name: Some(name), ..
        })
        | ShapeKind::Enum(EnumInfo {
            name: Some(name), ..
        }) => format!("decoder.readAdapted({}.ADAPTER)", java_type_name(name)),
        _ if is_bytes(shape) => "decoder.readBytes()".into(),
        _ => format!(
            "unsupportedDecode(\"{}\")",
            shape.type_identifier.replace('"', "\\\"")
        ),
    }
}

fn generate_descriptor(package: &str, name: &str, service: &ServiceDescriptor) -> String {
    let mut out = header(package);
    out.push_str("import java.util.List;\nimport org.facet.vox.MethodDescriptor;\nimport org.facet.vox.ServiceDescriptor;\n\n");
    let _ = writeln!(out, "public final class {name}ServiceDescriptor {{");
    for method in service.methods {
        let upper = java_constant(method.method_name);
        let args_adapter = format!("{}.ADAPTER", args_type_name(name, method));
        let (ok, err) = result_parts(method.return_shape);
        let ret_adapter = adapter_for(ok);
        let response_adapter = format!("{}.ADAPTER", response_type_name(name, method));
        let _ = if let Some(err) = err {
            writeln!(
                out,
                "  public static final MethodDescriptor {upper} = new MethodDescriptor(0x{:016x}L, \"{}\", {args_adapter}, {ret_adapter}, {}, {response_adapter});",
                crate::method_id(method),
                method.method_name,
                adapter_for(err)
            )
        } else {
            writeln!(
                out,
                "  public static final MethodDescriptor {upper} = new MethodDescriptor(0x{:016x}L, \"{}\", {args_adapter}, {ret_adapter}, null, {response_adapter});",
                crate::method_id(method),
                method.method_name
            )
        };
    }
    let methods = service
        .methods
        .iter()
        .map(|m| java_constant(m.method_name))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(
        out,
        "  public static final ServiceDescriptor INSTANCE = new ServiceDescriptor(\"{}\", List.of({methods}));",
        service.service_name
    );
    let _ = writeln!(out, "  private {name}ServiceDescriptor() {{}}");
    out.push_str("}\n");
    out
}

fn generate_handler(package: &str, name: &str, service: &ServiceDescriptor) -> String {
    let mut out = header(package);
    out.push_str("import java.util.concurrent.CompletableFuture;\nimport org.facet.vox.CallContext;\nimport org.facet.vox.VoxResult;\n\n");
    let _ = writeln!(out, "public interface {name}Handler {{");
    for method in service.methods {
        let args = method
            .args
            .iter()
            .map(|a| format!("{} {}", java_type(a.shape, false), java_ident(a.name)))
            .collect::<Vec<_>>()
            .join(", ");
        let args = if args.is_empty() {
            "CallContext context".to_string()
        } else {
            format!("CallContext context, {args}")
        };
        let return_ty = handler_return(method.return_shape);
        let _ = writeln!(
            out,
            "  CompletableFuture<{return_ty}> {}({args});",
            java_ident(method.method_name)
        );
    }
    out.push_str("}\n");
    out
}

fn generate_response_type(
    package: &str,
    name: &str,
    method: &MethodDescriptor,
) -> Result<String, JavaCodegenError> {
    let (ok_shape, error_shape) = result_parts(method.return_shape);
    let ok_type = boxed_java_type(ok_shape);
    let error_type = error_shape.map_or_else(|| "Void".to_string(), boxed_java_type);
    let ok_adapter = adapter_for(ok_shape);
    let error_adapter = error_shape.map(adapter_for);
    let module =
        phon_codegen::Module::from_shapes(&[method.response_wire_shape]).map_err(|cause| {
            error(
                method,
                &format!("response schema derivation failed: {cause}"),
            )
        })?;
    let root = module.roots.first().expect("one response root").id.as_u64();

    let mut out = header(package);
    out.push_str("import org.facet.phon.*;\nimport org.facet.vox.VoxResult;\n\n");
    let _ = writeln!(out, "public final class {name} {{");
    let _ = writeln!(
        out,
        "  private static final SchemaClosure SCHEMA = responseSchema();"
    );
    out.push_str("  private static SchemaClosure responseSchema() {\n    try {\n");
    let _ = writeln!(
        out,
        "      return SchemaClosure.fromCanonicalBytes(SchemaId.fromLong(0x{root:016x}L), new byte[][] {{"
    );
    for schema in &module.schemas {
        let bytes = schema_to_bytes(schema)
            .iter()
            .map(|byte| format!("(byte)0x{byte:02x}"))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "        new byte[] {{{bytes}}},");
    }
    out.push_str(
        "      }, PhonLimits.defaults());\n    } catch (PhonException failure) {\n      throw new ExceptionInInitializerError(failure);\n    }\n  }\n",
    );
    let _ = writeln!(
        out,
        "  public static final PhonAdapter<VoxResult<{ok_type}, {error_type}>> ADAPTER = new PhonAdapter<>() {{"
    );
    out.push_str("    @Override public SchemaClosure schema() { return SCHEMA; }\n");
    let _ = writeln!(
        out,
        "    @Override public void encode(PhonEncoder encoder, VoxResult<{ok_type}, {error_type}> value) throws PhonException {{"
    );
    out.push_str(
        "      if (value.isSuccess()) {\n        encoder.writeU32(0);\n        encoder.writeAdapted(",
    );
    let _ = writeln!(
        out,
        "{ok_adapter}, value.success());\n        return;\n      }}"
    );
    out.push_str("      encoder.writeU32(1);\n      switch (value.kind()) {\n");
    if let Some(ref error_adapter) = error_adapter {
        let _ = writeln!(
            out,
            "        case APPLICATION_ERROR:\n          encoder.writeU32(0);\n          encoder.writeAdapted({error_adapter}, value.applicationError());\n          return;"
        );
    } else {
        out.push_str(
            "        case APPLICATION_ERROR:\n          throw new PhonException(PhonException.Kind.ENCODE, \"infallible method cannot encode an application error\");\n",
        );
    }
    out.push_str(
        "        case UNKNOWN_METHOD: encoder.writeU32(1); return;\n\
         case INVALID_PAYLOAD: encoder.writeU32(2); encoder.writeString(value.detail()); return;\n\
         case CANCELLED: encoder.writeU32(3); return;\n\
         case CONNECTION_CLOSED: encoder.writeU32(4); return;\n\
         case CONNECTION_SHUTDOWN: encoder.writeU32(5); return;\n\
         case SEND_FAILED: encoder.writeU32(6); return;\n\
         case TIMED_OUT: encoder.writeU32(7); return;\n\
         case INDETERMINATE: encoder.writeU32(8); return;\n\
         default: throw new PhonException(PhonException.Kind.ENCODE, \"invalid response result kind\");\n\
         }\n    }\n",
    );
    let _ = writeln!(
        out,
        "    @Override public VoxResult<{ok_type}, {error_type}> decode(PhonDecoder decoder) throws PhonException {{"
    );
    out.push_str("      long outer = decoder.readU32();\n      if (outer == 0) return VoxResult.success(decoder.readAdapted(");
    let _ = writeln!(out, "{ok_adapter}));");
    out.push_str(
        "      if (outer != 1) throw new PhonException(PhonException.Kind.MALFORMED, \"invalid Result discriminant\");\n      long error = decoder.readU32();\n      switch ((int) error) {\n",
    );
    if let Some(ref error_adapter) = error_adapter {
        let _ = writeln!(
            out,
            "        case 0: return VoxResult.applicationError(decoder.readAdapted({error_adapter}));"
        );
    } else {
        out.push_str(
            "        case 0: throw new PhonException(PhonException.Kind.MALFORMED, \"infallible method received User error\");\n",
        );
    }
    out.push_str(
        "        case 1: return VoxResult.infrastructure(VoxResult.Kind.UNKNOWN_METHOD);\n\
         case 2: return VoxResult.infrastructure(VoxResult.Kind.INVALID_PAYLOAD, decoder.readString());\n\
         case 3: return VoxResult.infrastructure(VoxResult.Kind.CANCELLED);\n\
         case 4: return VoxResult.infrastructure(VoxResult.Kind.CONNECTION_CLOSED);\n\
         case 5: return VoxResult.infrastructure(VoxResult.Kind.CONNECTION_SHUTDOWN);\n\
         case 6: return VoxResult.infrastructure(VoxResult.Kind.SEND_FAILED);\n\
         case 7: return VoxResult.infrastructure(VoxResult.Kind.TIMED_OUT);\n\
         case 8: return VoxResult.infrastructure(VoxResult.Kind.INDETERMINATE);\n\
         default: throw new PhonException(PhonException.Kind.MALFORMED, \"invalid VoxError discriminant\");\n\
         }\n    }\n  };\n",
    );
    let _ = writeln!(out, "  private {name}() {{}}");
    out.push_str("}\n");
    Ok(out)
}

fn generate_dispatcher(package: &str, name: &str, service: &ServiceDescriptor) -> String {
    let mut out = header(package);
    out.push_str("import java.util.concurrent.CompletableFuture;\nimport java.util.concurrent.CompletionException;\nimport org.facet.phon.*;\nimport org.facet.vox.*;\n\n");
    let _ = writeln!(
        out,
        "public final class {name}Dispatcher implements ServiceDispatcher {{"
    );
    let _ = writeln!(out, "  private final {name}Handler handler;");
    let _ = writeln!(
        out,
        "  public {name}Dispatcher({name}Handler handler) {{ this.handler = java.util.Objects.requireNonNull(handler); }}"
    );
    let _ = writeln!(
        out,
        "  @Override public ServiceDescriptor descriptor() {{ return {name}ServiceDescriptor.INSTANCE; }}"
    );
    out.push_str(
        "  @Override public CompletableFuture<Void> dispatch(InboundCall call) {\n    try {\n",
    );
    for method in service.methods {
        let constant = java_constant(method.method_name);
        let tuple_ty = args_type_name(name, method);
        let invoke_args = method
            .args
            .iter()
            .map(|arg| format!("args.{}()", java_ident(arg.name)))
            .collect::<Vec<_>>()
            .join(", ");
        let invoke_args = if invoke_args.is_empty() {
            "call.context()".to_string()
        } else {
            format!("call.context(), {invoke_args}")
        };
        let (_, error_shape) = result_parts(method.return_shape);
        let response_ty = response_type_name(name, method);
        let _ = writeln!(
            out,
            "      if (call.method().id() == {name}ServiceDescriptor.{constant}.id()) {{"
        );
        let _ = writeln!(
            out,
            "        {tuple_ty} args = PhonCodec.decode({tuple_ty}.ADAPTER, call.encodedArguments(), PhonLimits.defaults());"
        );
        if error_shape.is_some() {
            let _ = writeln!(
                out,
                "        return handler.{}({invoke_args}).thenAccept(value -> {{\n          try {{\n            call.respond(PhonCodec.encode({response_ty}.ADAPTER, value, PhonLimits.defaults()));\n          }} catch (PhonException error) {{\n            throw new CompletionException(error);\n          }}\n        }});",
                java_ident(method.method_name)
            );
        } else {
            let _ = writeln!(
                out,
                "        return handler.{}({invoke_args}).thenAccept(value -> {{\n          try {{\n            call.respond(PhonCodec.encode({response_ty}.ADAPTER, VoxResult.success(value), PhonLimits.defaults()));\n          }} catch (PhonException error) {{\n            throw new CompletionException(error);\n          }}\n        }});",
                java_ident(method.method_name)
            );
        }
        out.push_str("      }\n");
    }
    out.push_str("      return CompletableFuture.failedFuture(new VoxException(\"unknown method \" + call.method().id()));\n    } catch (Exception error) {\n      return CompletableFuture.failedFuture(error);\n    }\n  }\n}\n");
    out
}

fn generate_client(package: &str, name: &str, service: &ServiceDescriptor) -> String {
    let mut out = header(package);
    out.push_str("import java.util.concurrent.CompletableFuture;\nimport java.util.concurrent.CompletionException;\nimport org.facet.phon.*;\nimport org.facet.vox.*;\n\n");
    let _ = writeln!(out, "public final class {name}Client {{");
    out.push_str("  private final ServiceLane lane;\n");
    let _ = writeln!(
        out,
        "  public {name}Client(ServiceLane lane) {{ this.lane = java.util.Objects.requireNonNull(lane); }}"
    );
    for method in service.methods {
        let args = method
            .args
            .iter()
            .map(|a| format!("{} {}", java_type(a.shape, false), java_ident(a.name)))
            .collect::<Vec<_>>()
            .join(", ");
        let return_ty = handler_return(method.return_shape);
        let method_name = java_ident(method.method_name);
        let constant = java_constant(method.method_name);
        let tuple_ty = args_type_name(name, method);
        let (_, error_shape) = result_parts(method.return_shape);
        let response_ty = response_type_name(name, method);
        let wire_result_ty = wire_result_type(method.return_shape);
        let _ = writeln!(
            out,
            "  public CompletableFuture<{return_ty}> {method_name}({args}) {{ return {method_name}({}{sep}CallOptions.defaults()); }}",
            args_names(method),
            sep = if args.is_empty() { "" } else { ", " }
        );
        let with_opts = if args.is_empty() {
            "CallOptions options".to_string()
        } else {
            format!("{args}, CallOptions options")
        };
        let _ = writeln!(
            out,
            "  public CompletableFuture<{return_ty}> {method_name}({with_opts}) {{"
        );
        let _ = writeln!(
            out,
            "    try {{\n      byte[] encoded = PhonCodec.encode({tuple_ty}.ADAPTER, new {}({}), PhonLimits.defaults());",
            tuple_ty,
            args_names(method)
        );
        if error_shape.is_some() {
            let _ = writeln!(
                out,
                "      return lane.call({name}ServiceDescriptor.{constant}, encoded, options).thenApply(bytes -> {{\n        try {{\n          {wire_result_ty} result = PhonCodec.decode({response_ty}.ADAPTER, bytes, PhonLimits.defaults());\n          if (result.isInfrastructureError()) throw remoteFailure(result);\n          return result;\n        }} catch (PhonException error) {{\n          throw new CompletionException(error);\n        }}\n      }});\n    }} catch (PhonException error) {{\n      return CompletableFuture.failedFuture(error);\n    }}"
            );
        } else {
            let _ = writeln!(
                out,
                "      return lane.call({name}ServiceDescriptor.{constant}, encoded, options).thenApply(bytes -> {{\n        try {{\n          {wire_result_ty} result = PhonCodec.decode({response_ty}.ADAPTER, bytes, PhonLimits.defaults());\n          if (!result.isSuccess()) throw remoteFailure(result);\n          return result.success();\n        }} catch (PhonException error) {{\n          throw new CompletionException(error);\n        }}\n      }});\n    }} catch (PhonException error) {{\n      return CompletableFuture.failedFuture(error);\n    }}"
            );
        }
        out.push_str("  }\n");
    }
    out.push_str(
        "  private static CompletionException remoteFailure(VoxResult<?, ?> result) {\n\
         String detail = result.detail() == null ? \"\" : \": \" + result.detail();\n\
         return new CompletionException(new VoxException(\"remote Vox error \" + result.kind() + detail));\n\
         }\n}\n",
    );
    out
}

fn args_names(method: &MethodDescriptor) -> String {
    method
        .args
        .iter()
        .map(|a| java_ident(a.name))
        .collect::<Vec<_>>()
        .join(", ")
}

fn args_type_name(service_name: &str, method: &MethodDescriptor) -> String {
    format!("{service_name}{}Args", upper_camel(method.method_name))
}

fn response_type_name(service_name: &str, method: &MethodDescriptor) -> String {
    format!("{service_name}{}Response", upper_camel(method.method_name))
}

fn result_parts(shape: &'static Shape) -> (&'static Shape, Option<&'static Shape>) {
    match classify_shape(shape) {
        ShapeKind::Result { ok, err } => (ok, Some(err)),
        _ => (shape, None),
    }
}

fn handler_return(shape: &'static Shape) -> String {
    let (ok, err) = result_parts(shape);
    match err {
        Some(err) => format!(
            "VoxResult<{}, {}>",
            boxed_java_type(ok),
            boxed_java_type(err)
        ),
        None => boxed_java_type(ok),
    }
}

fn wire_result_type(shape: &'static Shape) -> String {
    let (ok, err) = result_parts(shape);
    format!(
        "VoxResult<{}, {}>",
        boxed_java_type(ok),
        err.map_or_else(|| "Void".to_string(), boxed_java_type)
    )
}

fn adapter_for(shape: &'static Shape) -> String {
    match classify_shape(shape) {
        ShapeKind::Struct(StructInfo {
            name: Some(name), ..
        })
        | ShapeKind::Enum(EnumInfo {
            name: Some(name), ..
        }) => {
            format!("{}.ADAPTER", java_type_name(name))
        }
        ShapeKind::Scalar(scalar) => {
            format!("PrimitiveAdapters.{}", primitive_adapter_name(scalar))
        }
        _ if is_bytes(shape) => "PrimitiveAdapters.BYTES".to_string(),
        _ => format!(
            "PrimitiveAdapters.unsupported(\"{}\")",
            shape.type_identifier
        ),
    }
}

fn generate_primitive_adapters(package: &str) -> String {
    let mut out = header(package);
    out.push_str("import org.facet.phon.*;\n\n");
    out.push_str("final class PrimitiveAdapters {\n");
    let adapters = [
        (
            "STRING",
            "String",
            "STRING",
            "encoder.writeString(value);",
            "decoder.readString()",
        ),
        (
            "BOOL",
            "Boolean",
            "BOOL",
            "encoder.writeBool(value);",
            "decoder.readBool()",
        ),
        (
            "I32",
            "Integer",
            "I32",
            "encoder.writeI32(value);",
            "decoder.readI32()",
        ),
        (
            "I64",
            "Long",
            "I64",
            "encoder.writeI64(value);",
            "decoder.readI64()",
        ),
        (
            "U8",
            "Integer",
            "U8",
            "encoder.writeU8(value);",
            "decoder.readU8()",
        ),
        (
            "U16",
            "Integer",
            "U16",
            "encoder.writeU16(value);",
            "decoder.readU16()",
        ),
        (
            "U32",
            "Long",
            "U32",
            "encoder.writeU32(value);",
            "decoder.readU32()",
        ),
        (
            "F32",
            "Float",
            "F32",
            "encoder.writeF32(value);",
            "decoder.readF32()",
        ),
        (
            "F64",
            "Double",
            "F64",
            "encoder.writeF64(value);",
            "decoder.readF64()",
        ),
        (
            "BYTES",
            "byte[]",
            "BYTES",
            "encoder.writeBytes(value);",
            "decoder.readBytes()",
        ),
    ];
    for (field, ty, primitive, encode, decode) in adapters {
        let _ = writeln!(
            out,
            "  static final PhonAdapter<{ty}> {field} = new PhonAdapter<>() {{"
        );
        let _ = writeln!(
            out,
            "    @Override public SchemaClosure schema() {{ return SchemaClosure.uncheckedOf(Schema.primitive(Schema.Primitive.{primitive})); }}"
        );
        let _ = writeln!(
            out,
            "    @Override public void encode(PhonEncoder encoder, {ty} value) throws PhonException {{ {encode} }}"
        );
        let _ = writeln!(
            out,
            "    @Override public {ty} decode(PhonDecoder decoder) throws PhonException {{ return {decode}; }}"
        );
        out.push_str("  };\n");
    }
    out.push_str("  static <T> PhonAdapter<T> unsupported(String shape) { throw new IllegalArgumentException(\"unsupported generated adapter \" + shape); }\n");
    out.push_str("  private PrimitiveAdapters() {}\n}\n");
    out
}

fn primitive_adapter_name(scalar: ScalarType) -> &'static str {
    match scalar {
        ScalarType::Bool => "BOOL",
        ScalarType::U8 => "U8",
        ScalarType::U16 => "U16",
        ScalarType::U32 => "U32",
        ScalarType::I8 | ScalarType::I16 | ScalarType::I32 => "I32",
        ScalarType::I64 => "I64",
        ScalarType::F32 => "F32",
        ScalarType::F64 => "F64",
        ScalarType::Str | ScalarType::String | ScalarType::CowStr | ScalarType::Char => "STRING",
        _ => "I64",
    }
}

fn java_type(shape: &'static Shape, boxed: bool) -> String {
    if is_bytes(shape) {
        return "byte[]".to_string();
    }
    match classify_shape(shape) {
        ShapeKind::Scalar(s) => scalar_java(s, boxed),
        ShapeKind::Option { inner } => format!("java.util.Optional<{}>", boxed_java_type(inner)),
        ShapeKind::List { element }
        | ShapeKind::Slice { element }
        | ShapeKind::Array { element, .. } => {
            format!("java.util.List<{}>", boxed_java_type(element))
        }
        ShapeKind::Set { element } => format!("java.util.Set<{}>", boxed_java_type(element)),
        ShapeKind::Map { key, value } => format!(
            "java.util.Map<{}, {}>",
            boxed_java_type(key),
            boxed_java_type(value)
        ),
        ShapeKind::Struct(StructInfo {
            name: Some(name), ..
        })
        | ShapeKind::Enum(EnumInfo {
            name: Some(name), ..
        }) => java_type_name(name),
        ShapeKind::Tuple { elements } => format!("Tuple{}", elements.len()),
        ShapeKind::TupleStruct { fields } => format!("Tuple{}", fields.len()),
        ShapeKind::Result { ok, err } => format!(
            "VoxResult<{}, {}>",
            boxed_java_type(ok),
            boxed_java_type(err)
        ),
        ShapeKind::Pointer { pointee } => java_type(pointee, boxed),
        _ => "Object".to_string(),
    }
}

fn boxed_java_type(shape: &'static Shape) -> String {
    java_type(shape, true)
}

fn scalar_java(scalar: ScalarType, boxed: bool) -> String {
    match scalar {
        ScalarType::Bool => if boxed { "Boolean" } else { "boolean" }.into(),
        ScalarType::U8 | ScalarType::U16 | ScalarType::I8 | ScalarType::I16 | ScalarType::I32 => {
            if boxed { "Integer" } else { "int" }.into()
        }
        ScalarType::U32
        | ScalarType::I64
        | ScalarType::U64
        | ScalarType::ISize
        | ScalarType::USize => if boxed { "Long" } else { "long" }.into(),
        ScalarType::F32 => if boxed { "Float" } else { "float" }.into(),
        ScalarType::F64 => if boxed { "Double" } else { "double" }.into(),
        ScalarType::U128 | ScalarType::I128 => "java.math.BigInteger".into(),
        ScalarType::Char | ScalarType::Str | ScalarType::String | ScalarType::CowStr => {
            "String".into()
        }
        ScalarType::Unit => "Void".into(),
        _ => "Object".into(),
    }
}

fn is_reference(shape: &'static Shape) -> bool {
    !matches!(
        classify_shape(shape),
        ShapeKind::Scalar(
            ScalarType::Bool
                | ScalarType::U8
                | ScalarType::U16
                | ScalarType::U32
                | ScalarType::U64
                | ScalarType::USize
                | ScalarType::I8
                | ScalarType::I16
                | ScalarType::I32
                | ScalarType::I64
                | ScalarType::ISize
                | ScalarType::F32
                | ScalarType::F64
                | ScalarType::Char
        )
    )
}

fn is_option(shape: &'static Shape) -> bool {
    matches!(classify_shape(shape), ShapeKind::Option { .. })
}

fn java_type_name(name: &str) -> String {
    name.rsplit("::")
        .next()
        .unwrap_or(name)
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '_')
        .collect()
}

fn upper_camel(name: &str) -> String {
    name.split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            chars
                .next()
                .map(|c| c.to_ascii_uppercase().to_string() + chars.as_str())
                .unwrap_or_default()
        })
        .collect()
}

fn java_ident(name: &str) -> String {
    let mut out = String::new();
    for (i, part) in name.split('_').enumerate() {
        if i == 0 {
            out.push_str(part);
        } else {
            let mut chars = part.chars();
            if let Some(c) = chars.next() {
                out.push(c.to_ascii_uppercase());
            }
            out.extend(chars);
        }
    }
    match out.as_str() {
        "class" | "enum" | "interface" | "return" | "default" | "switch" | "case" | "new" => {
            format!("{out}_")
        }
        _ => out,
    }
}

fn java_constant(name: &str) -> String {
    name.chars()
        .flat_map(|c| {
            if c.is_ascii_uppercase() {
                vec!['_', c]
            } else {
                vec![c.to_ascii_uppercase()]
            }
        })
        .collect::<String>()
        .trim_start_matches('_')
        .to_string()
}

fn java_enum_constant(name: &str) -> String {
    java_constant(name)
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::{Path, PathBuf};
    use std::process::Command;
    use std::time::{SystemTime, UNIX_EPOCH};

    use facet::Facet;
    use vox_types::{MethodDescriptorOptions, Rx, ServiceDescriptor, method_descriptor};

    use super::{generate_service, generate_wire_schemas};

    #[derive(Clone, Debug, Facet)]
    struct NestedRequest {
        message: String,
    }

    #[derive(Clone, Debug, Facet)]
    struct NestedResponse {
        echoed: String,
    }

    #[derive(Clone, Debug, Facet)]
    #[repr(u8)]
    enum DivideByZero {
        Zero = 0,
    }

    fn fixture_service() -> ServiceDescriptor {
        let echo = method_descriptor::<(String,), String>(
            "Review",
            "echo",
            &["value"],
            &[None],
            MethodDescriptorOptions {
                response_wire_shape: <Result<String, vox_types::VoxError> as Facet>::SHAPE,
                doc: None,
            },
        );
        let inspect = method_descriptor::<(NestedRequest,), NestedResponse>(
            "Review",
            "inspect",
            &["request"],
            &[None],
            MethodDescriptorOptions {
                response_wire_shape: <Result<NestedResponse, vox_types::VoxError> as Facet>::SHAPE,
                doc: None,
            },
        );
        let divide = method_descriptor::<(i64, i64), Result<i64, DivideByZero>>(
            "Review",
            "divide",
            &["dividend", "divisor"],
            &[None, None],
            MethodDescriptorOptions {
                response_wire_shape:
                    <Result<i64, vox_types::VoxError<DivideByZero>> as Facet>::SHAPE,
                doc: None,
            },
        );
        let methods = Box::leak(vec![echo, inspect, divide].into_boxed_slice());
        ServiceDescriptor {
            service_name: "Review",
            methods,
            doc: None,
        }
    }

    #[test]
    fn java_generation_is_deterministic_and_emits_frozen_surfaces() {
        let service = fixture_service();
        let first = generate_service(&service).expect("supported service");
        let second = generate_service(&service).expect("repeat generation");
        assert_eq!(first, second);
        let all = first
            .iter()
            .map(|file| file.source.as_str())
            .collect::<String>();
        assert!(all.contains("public final class NestedRequest"));
        assert!(all.contains("public static final PhonAdapter<NestedRequest> ADAPTER"));
        assert!(all.contains("public interface ReviewHandler"));
        assert!(all.contains("CompletableFuture<String> echo("));
        assert!(all.contains("CompletableFuture<VoxResult<Long, DivideByZero>> divide("));
        assert!(all.contains("public final class ReviewDispatcher implements ServiceDispatcher"));
        assert!(all.contains("public final class ReviewClient"));
        assert!(all.contains("0x"));
    }

    #[test]
    fn java_wire_schemas_are_derived_deterministically_from_rust_shapes() {
        let first = generate_wire_schemas().expect("wire schemas");
        let second = generate_wire_schemas().expect("repeat wire schemas");
        assert_eq!(first, second);
        assert_eq!(
            first
                .iter()
                .map(|file| file.relative_path.as_str())
                .collect::<Vec<_>>(),
            ["HandshakeWireSchemas.java", "MessageWireSchemas.java"]
        );
        assert!(
            first
                .iter()
                .all(|file| file.source.contains("CANONICAL_SCHEMAS"))
        );
        assert!(first[0].source.contains("HANDSHAKE_MESSAGE_SCHEMA_ID"));
        assert!(first[1].source.contains("MESSAGE_SCHEMA_ID"));
    }

    #[test]
    fn java_generation_rejects_channels_with_service_and_method() {
        let stream = method_descriptor::<(Rx<String>,), ()>(
            "UnsupportedService",
            "stream",
            &["input"],
            &[Some(<String as Facet>::SHAPE)],
            MethodDescriptorOptions {
                response_wire_shape: <Result<(), vox_types::VoxError> as Facet>::SHAPE,
                doc: None,
            },
        );
        let methods = Box::leak(vec![stream].into_boxed_slice());
        let service = ServiceDescriptor {
            service_name: "UnsupportedService",
            methods,
            doc: None,
        };
        let error = generate_service(&service).expect_err("channels are unsupported");
        assert_eq!(error.service, "UnsupportedService");
        assert_eq!(error.method, "stream");
        assert!(error.to_string().contains("channels"));
    }

    #[test]
    fn generated_fixture_compiles_with_javac_release_17() {
        let dir = unique_temp_dir();
        let generated = dir.join("org/facet/vox/generated");
        fs::create_dir_all(&generated).expect("create generated package");
        for file in generate_service(&fixture_service()).expect("generate fixture") {
            fs::write(generated.join(file.relative_path), file.source).expect("write Java file");
        }
        write_compile_stubs(&dir);

        let sources = collect_java_files(&dir);
        let classes = dir.join("classes");
        fs::create_dir_all(&classes).expect("create classes");
        let output = Command::new("javac")
            .arg("--release")
            .arg("17")
            .arg("-d")
            .arg(&classes)
            .args(&sources)
            .output()
            .expect("JDK 17+ javac must be available for the Java generator gate");
        if !output.status.success() {
            panic!(
                "javac --release 17 failed:\nstdout:\n{}\nstderr:\n{}",
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr)
            );
        }
        fs::remove_dir_all(&dir).expect("remove Java compile fixture");
    }

    fn unique_temp_dir() -> PathBuf {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("clock")
            .as_nanos();
        std::env::temp_dir().join(format!("vox-java-codegen-{}-{nonce}", std::process::id()))
    }

    fn collect_java_files(root: &Path) -> Vec<PathBuf> {
        fn visit(path: &Path, files: &mut Vec<PathBuf>) {
            for entry in fs::read_dir(path).expect("read fixture dir") {
                let path = entry.expect("dir entry").path();
                if path.is_dir() {
                    visit(&path, files);
                } else if path.extension().is_some_and(|ext| ext == "java") {
                    files.push(path);
                }
            }
        }
        let mut files = Vec::new();
        visit(root, &mut files);
        files.sort();
        files
    }

    fn write_compile_stubs(root: &Path) {
        let files = [
            (
                "org/facet/phon/PhonAdapter.java",
                "package org.facet.phon; public interface PhonAdapter<T> { SchemaClosure schema(); void encode(PhonEncoder e,T v) throws PhonException; T decode(PhonDecoder d) throws PhonException; }",
            ),
            (
                "org/facet/phon/SchemaClosure.java",
                "package org.facet.phon; public final class SchemaClosure { public static SchemaClosure uncheckedOf(Schema s,Schema... r){return new SchemaClosure();} public static SchemaClosure fromCanonicalBytes(SchemaId id,byte[][] b,PhonLimits l)throws PhonException{return new SchemaClosure();} }",
            ),
            (
                "org/facet/phon/SchemaId.java",
                "package org.facet.phon; public final class SchemaId { public static SchemaId fromLong(long v){return new SchemaId();} }",
            ),
            (
                "org/facet/phon/Schema.java",
                "package org.facet.phon; import java.util.*; public final class Schema { public enum Primitive { STRING,BOOL,I32,I64,U8,U16,U32,F32,F64,BYTES } public static Schema primitive(Primitive p){return new Schema(null,List.of(),null);} public Schema(SchemaId i,List<Object> p,Object k){} public static final class Ref { public static Ref concrete(SchemaId i){return new Ref();} } public static final class Field { public Field(String n,Ref r,boolean q){} } public static final class RecordKind { public RecordKind(String n,List<Field> f){} } public static final class TupleKind { public TupleKind(List<Ref> r){} } public static final class EnumKind { public EnumKind(String n,List<Variant> v){} } public static final class Variant { public Variant(String n,int i,Payload p){} } public static final class Payload { public static Payload unit(){return new Payload();} } }",
            ),
            (
                "org/facet/phon/PhonException.java",
                "package org.facet.phon; public class PhonException extends Exception { public enum Kind { ENCODE,DECODE,MALFORMED } public PhonException(Kind k,String m){super(m);} }",
            ),
            (
                "org/facet/phon/PhonEncoder.java",
                "package org.facet.phon; public final class PhonEncoder { public void writeBool(boolean v){} public void writeU8(int v){} public void writeU16(int v){} public void writeU32(long v){} public void writeI8(int v){} public void writeI16(int v){} public void writeI32(int v){} public void writeI64(long v){} public void writeF32(float v){} public void writeF64(double v){} public void writeChar(char v){} public void writeString(String v){} public void writeBytes(byte[] v){} public <T> void writeAdapted(PhonAdapter<T> a,T v){} }",
            ),
            (
                "org/facet/phon/PhonDecoder.java",
                "package org.facet.phon; public final class PhonDecoder { public boolean readBool(){return false;} public int readU8(){return 0;} public int readU16(){return 0;} public long readU32(){return 0;} public int readI8(){return 0;} public int readI16(){return 0;} public int readI32(){return 0;} public long readI64(){return 0;} public float readF32(){return 0;} public double readF64(){return 0;} public char readChar(){return 0;} public String readString(){return null;} public byte[] readBytes(){return null;} public <T> T readAdapted(PhonAdapter<T> a){return null;} }",
            ),
            (
                "org/facet/phon/PhonLimits.java",
                "package org.facet.phon; public final class PhonLimits { public static PhonLimits defaults(){return new PhonLimits();} }",
            ),
            (
                "org/facet/phon/PhonCodec.java",
                "package org.facet.phon; public final class PhonCodec { public static <T> byte[] encode(PhonAdapter<T> a,T v,PhonLimits l)throws PhonException{return new byte[0];} public static <T> T decode(PhonAdapter<T> a,byte[] b,PhonLimits l)throws PhonException{return null;} }",
            ),
            (
                "org/facet/vox/MethodDescriptor.java",
                "package org.facet.vox; import org.facet.phon.*; public final class MethodDescriptor { private final long id; private final PhonAdapter<?> a,r,w; public MethodDescriptor(long i,String n,PhonAdapter<?> a,PhonAdapter<?> r){this(i,n,a,r,null,r);} public MethodDescriptor(long i,String n,PhonAdapter<?> a,PhonAdapter<?> r,PhonAdapter<?> e){this(i,n,a,r,e,r);} public MethodDescriptor(long i,String n,PhonAdapter<?> a,PhonAdapter<?> r,PhonAdapter<?> e,PhonAdapter<?> w){id=i;this.a=a;this.r=r;this.w=w;} public long id(){return id;} public PhonAdapter argumentAdapter(){return a;} public PhonAdapter returnAdapter(){return r;} public PhonAdapter responseWireAdapter(){return w;} }",
            ),
            (
                "org/facet/vox/ServiceDescriptor.java",
                "package org.facet.vox; import java.util.*; public final class ServiceDescriptor { public ServiceDescriptor(String n,List<MethodDescriptor> m){} }",
            ),
            (
                "org/facet/vox/CallContext.java",
                "package org.facet.vox; public final class CallContext {}",
            ),
            (
                "org/facet/vox/VoxResult.java",
                "package org.facet.vox; public final class VoxResult<O,E> { public enum Kind { SUCCESS,APPLICATION_ERROR,UNKNOWN_METHOD,INVALID_PAYLOAD,CANCELLED,CONNECTION_CLOSED,CONNECTION_SHUTDOWN,SEND_FAILED,TIMED_OUT,INDETERMINATE } public static <O,E> VoxResult<O,E> success(O v){return new VoxResult<>();} public static <O,E> VoxResult<O,E> applicationError(E v){return new VoxResult<>();} public static <O,E> VoxResult<O,E> infrastructure(Kind k){return new VoxResult<>();} public static <O,E> VoxResult<O,E> infrastructure(Kind k,String d){return new VoxResult<>();} public Kind kind(){return Kind.SUCCESS;} public boolean isSuccess(){return true;} public boolean isInfrastructureError(){return false;} public String detail(){return null;} public O success(){return null;} public E applicationError(){return null;} }",
            ),
            (
                "org/facet/vox/VoxException.java",
                "package org.facet.vox; public class VoxException extends Exception { public VoxException(String m){super(m);} }",
            ),
            (
                "org/facet/vox/ServiceDispatcher.java",
                "package org.facet.vox; import java.util.concurrent.*; public interface ServiceDispatcher { ServiceDescriptor descriptor(); CompletableFuture<Void> dispatch(InboundCall c); }",
            ),
            (
                "org/facet/vox/InboundCall.java",
                "package org.facet.vox; public final class InboundCall { public MethodDescriptor method(){return null;} public byte[] encodedArguments(){return null;} public CallContext context(){return null;} public void respond(byte[] b){} }",
            ),
            (
                "org/facet/vox/ServiceLane.java",
                "package org.facet.vox; import java.util.concurrent.*; public final class ServiceLane { public CompletableFuture<byte[]> call(MethodDescriptor m,byte[] b,CallOptions o){return null;} }",
            ),
            (
                "org/facet/vox/CallOptions.java",
                "package org.facet.vox; public final class CallOptions { public static CallOptions defaults(){return new CallOptions();} }",
            ),
        ];
        for (relative, source) in files {
            let path = root.join(relative);
            fs::create_dir_all(path.parent().expect("parent")).expect("create stub package");
            fs::write(path, source).expect("write compile stub");
        }
    }
}
